backend:
  name: github
  repo: BergenSwampExperience/bergen-swamp
  open_authoring: true

  branch: master # Branch to update (optional; defaults to master)
# This line should *not* be indented
media_folder: "assets/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads
site_url: https://bergenswamp.netlify.app
logo_url: https://bergenswamp.org/img/BSPS_logo_sm.jpg
publish_mode: editorial_workflow
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    preview_path: "{{slug}}"
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Properties", name: "category", widget: "relation", collection: "categories", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Trails", name: "trails", widget: "relation", collection: "trails", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Stops", name: "stops", widget: "relation", collection: "stops", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "featureImage", widget: "image"}
      - {label: "Video", name: "video", widget: "file", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        field: {label: Name, name: name, widget: string, default: ["Trail 1", "Pocock Trail"]}
      
  - name: "categories"
    label: "Properties"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
  - name: "trails"
    label: "Trails"
    folder: "content/trails"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Properties", name: "property", widget: "relation", collection: "categories", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
    
  - name: "stops"
    label: "Stops"
    folder: "content/stops"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Trails", name: "trails", widget: "relation", collection: "trails", searchFields: ["name"], valueField: "name", multiple: true}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "markdown"}
